// Code generated by andurel. DO NOT EDIT.
// This file contains constructor functions for SQLC parameters.
// These functions are automatically updated during schema refresh operations.

package db

import (
	"github.com/google/uuid"
)

// Constructor functions for SQLC parameters - these get updated during refresh
// to make schema changes compiler-enforced and visible

func NewInsertUserParams(
	email string,
	isadmin int64,
	password []byte,
) InsertUserParams {
	return InsertUserParams{
		ID:       uuid.New().String(),
		Email:    email,
		IsAdmin:  isadmin,
		Password: password,
	}
}

func NewUpdateUserParams(
	id string,
	email string,
	isadmin int64,
	password []byte,
) UpdateUserParams {
	return UpdateUserParams{
		ID:       id,
		Email:    email,
		IsAdmin:  isadmin,
		Password: password,
	}
}

func NewQueryPaginatedUsersParams(limit, offset int64) QueryPaginatedUsersParams {
	return QueryPaginatedUsersParams{
		Limit:  limit,
		Offset: offset,
	}
}
